<?
$PERM["lichnyy-kabinet-prodavtsa"]["8"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["6"]="R";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["8"]="W";
$PERM["lichnyy-kabinet-pokupatelya"]["7"]="R";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["/"]["8"]="W";
$PERM["/"]["*"]="R";
$PERM[".git"]["*"]="D";
$PERM["bitrix"]["2"]="D";
$PERM["bitrix"]["8"]="D";
$PERM["bitrix"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
?>